project:
  type: website

website:
  page-navigation: true
  title: "STA 210 - Fall 2022"
  description: "Homepage for STA 210 - Regression Analysis at Duke University, Spring 2022."
  site-url: "https://sta210-fa22.netlify.app"

  repo-url: https://github.com/sta210-fa22/website
  repo-actions: [edit, issue]
  
  opengraph: true
  twitter-card:
    creator: "@MT_statistics"
    image: "images/twitter-card.png"

  page-footer:
    background: "#7eb7c2"
    left: |
      &copy; Copyright 2022, Maria Tackett
    right: |
      This site is built with [Quarto](https://quarto.org/)<br>

  sidebar:
    background: "#7eb7c2"
    logo: "images/logo.png"
    align: center
    tools: 
      - icon: github
        href: https://github.com/sta210-fa22
        text: "GitHub organization"
      - icon: code-square
        href: https://cmgr.oit.duke.edu/containers
        text: "RStudio Containers"
      - icon: person-fill
        text: "Sakai"
        menu:
          - text: Discussion forum
            url: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/tool/13b6446a-a6c6-4222-8cfb-c36d1f70802b
          - text: Gradescope
            url: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/page/aec742dc-2972-4f02-a35b-1dd3315af889
          - text: Gradebook
            url: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/tool/69078433-67a6-4054-a2e7-9e6c202ecdc3/
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: support.qmd
        text: Support
      - section: Computing
        contents: 
        - href: computing-access.qmd
          text: Access
        - href: computing-troubleshooting.qmd
          text: Troubleshooting
        - href: computing-r-resources.qmd
          text: R resources
      - href: links.qmd
        text: Useful links

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    mainfont: "Open Sans"
    code-copy: true
    code-overflow: wrap
    toc: true

execute:
  freeze: auto

editor: visual    
    



